### ISSUE TITLE
General Attribute Issues: (Gentle Fawn; Flamingo oh, oh, oh; Trumpet Skeleton)

### ISSUE THREAD

**Issue by Blunder-G** [FaeCraft/Flamingo#10] opened 2021-06-10 16:50 UTC
Your mods causes issues on loading. i'm using MultiMC and this three mods have red colors (important) I know, Trumpet Skeleton
(Fabric) not your mod but i think it uses your codes.

Error:

[19:41:09] [main/ERROR]: Entity trumpet-skeleton:trumpet_skeleton has no attributes
[19:41:09] [main/ERROR]: Entity gentlefawn:deer has no attributes
[19:41:09] [main/ERROR]: Entity flamingo_ooo:flamingo has no attributes

**Comment by gdude2002** [comment] 2021-06-10 16:52
This isn't something that causes any problems - we've been unable to find a solution to it.

Duplicate of https://github.com/FaeCraft/GentleFawn/issues/6

**Closed as completed by gdude2002** 2021-06-10 16:52 UTC
Labels: invalid
